spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application:
    name: user-application
server:
  port: 8081

springdoc:
  swagger-ui:
    path: "/swagger"